export default {
    accessToken : '',
    myinfo: null,
    codeClasses: [],
    codeClass: null,
    codeDetails: [],
    codeDetail: null,
    jobCodes: [],
    members: [],
    member: null,
    boards: [],
    board: null,
    notices: [],
    notice: null,
    items: [],
    item: null,
    chargeCoins: [],
    payCoins: [],
    userItems: [],
    userItem: null,
    pdsItems: [],
    pdsItem: null,
    attachments: []
}